# Generated by Django 5.0 on 2024-01-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='tasks',
            name='app1_tasks_title_8c4c7a_idx',
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['title'], name='app1_tasks_title_032cbe_idx'),
        ),
    ]
